#### DoD Vanilla Changes ####
# Skeleton - Ice
SkeletonWarriorIce:
  size: 0.02
  health: 13.0
  damage: 5.7
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 13
        1: 13.65
        2: 14.3
        3: 14.95
        4: 15.6
        5: 16.35
    damage: 
        0: 5.7
        1: 6.3
        2: 6.9
        3: 10.5
        4: 11.6
        5: 12.3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Ice Drake
Ice Drake:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Dire Wolf
Dire Wolf:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Frozen Bones
Frozen Bones:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Frigid Spider
Frigid Spider:
  size: 0.02
  health: 5
  damage: 2.37
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 5
        1: 5.25
        2: 5.5
        3: 5.75
        4: 6
        5: 6.25
    damage: 
        0: 2.37
        1: 2.61
        2: 2.85
        3: 3.09
        4: 3.23
        5: 3.47
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Gray Wolf
Gray Wolf:
  size: 0
  infusion: 
      Fire: 0
      Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Black Werewolf
WereWolfBlack:
  size: 0.02
  effect:
    Splitting: 0
  infusion: 
    Fire: 0
    Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Grey Werewolf
WereWolfDarkGrey:
  size: 0.02
  effect:
    Splitting: 0
  infusion: 
    Fire: 0
    Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Female Werewolf
WereWolfWhite:
  size: 0.02
  effect:
    Splitting: 0
  infusion: 
    Fire: 0
    Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Transformed Gray Wolf
WereWolfBlackArmored:
  size: 0.02
  effect:
    Splitting: 0
  infusion: 
    Fire: 0
    Frost: 14
  Deep North:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25