#### DoD Vanilla Changes ####
#Greyling
Greyling:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Boar
Boar:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Neck
Neck:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf
Greydwarf:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Shaman
Greydwarf Shaman:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Brute
Greydwarf Brute:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
#Skeleton
Skeleton:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Fuling
Fuling:
  size: 0.02
  Meadows:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25      
## Forest Wolf
Forest Wolf:
  size: 0.02
  Meadows:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25