#### DoD Vanilla Changes ####
# Voidling
Voidling:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 20
      Spirit: 10
      Poison: 0
      Chaos: 20
  Mistlands:
    health:
        0: 2
        1: 2.05
        2: 2.1
        3: 2.15
        4: 2.2
        5: 2.25
    damage: 
        0: 1.5
        1: 1.6
        2: 1.7
        3: 1.8
        4: 1.9
        5: 2
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Vilefang
Vilefang:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 0
      Spirit: 0
      Poison: 75
      Chaos: 0
  Mistlands:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Brown Spider
Brown Spider:
  size: 0.02
  health: 3.0
  damage: 1.75
  Mistlands:
    health:
        0: 3.0
        1: 3.15
        2: 3.3
        3: 3.45
        4: 3.6
        5: 3.75
    damage: 
        0: 1.75
        1: 1.92
        2: 2.09
        3: 2.26
        4: 2.43
        5: 2.6
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Forest Spider
Forest Spider:
  size: 0.02
  health: 3.0
  damage: 1.75
  Mistlands:
    health:
        0: 3.0
        1: 3.15
        2: 3.3
        3: 3.45
        4: 3.6
        5: 3.75
    damage: 
        0: 1.75
        1: 1.92
        2: 2.09
        3: 2.26
        4: 2.43
        5: 2.6
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Einherjar
Einherjar:
  size: 0
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 0
      Spirit: 25
      Poison: 0
      Chaos: 25
  Mistlands:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
# Forest Wendigo
WendigoForest:
  Mistlands:
    size: 0.02
    health:
        0: 1.25
        1: 1.3
        2: 1.35
        3: 1.4
        4: 1.45
        5: 1.5
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1.1
        1: 1.15
        2: 1.2
        3: 1.25
        4: 1.3
        5: 1.35
# Earth Elemental
Earth Elemental:
  Mistlands:
    size: 0.00
    health:
        0: 1.25
        1: 1.3
        2: 1.35
        3: 1.4
        4: 1.45
        5: 1.5
    damage: 
        0: 2
        1: 2.1
        2: 2.4
        3: 2.6
        4: 2.8
        5: 3
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1.1
        1: 1.15
        2: 1.2
        3: 1.25
        4: 1.3
        5: 1.35
        